IF NOT EXISTS(select * from sys.tables where name = 'TB_APARTAMENTO')
BEGIN
	CREATE TABLE TB_APARTAMENTO
	(
		 ApartamentoID INT PRIMARY KEY IDENTITY(1,1)
		,NumeroApartamento INT NOT NULL
		,TipoEstadia CHAR(1) NOT NULL
		,AndarPredio INT NOT NULL
		,PredioID INT FOREIGN KEY(PredioID) REFERENCES TB_PREDIO
	)
END
GO

ALTER TABLE TB_APARTAMENTO
ADD ValorApartamento DECIMAL(10,2) NOT NULL DEFAULT(0.00)

ALTER TABLE TB_APARTAMENTO
DROP COLUMN TipoEstadia 

ALTER TABLE TB_APARTAMENTO
ALTER COLUMN TipoEstadiaID INT FOREIGN KEY (TipoEstadiaID) REFERENCES TB_TIPOESTADIA NOT NULL

/*

OBS: TipoEstadia

A = Aluguel
P = Proprietário
T = Temporario

*/

ALTER TABLE TB_APARTAMENTO
ADD IsCadAutomatico BIT NOT NULL DEFAULT(0)