IF NOT EXISTS(select * from sys.tables  where name = 'TB_CONDOMINIO')
BEGIN
	CREATE TABLE TB_CONDOMINIO
	(
		 CondominioID INT PRIMARY KEY IDENTITY(1,1)
		,Nome VARCHAR(150) NOT NULL
		,QtdBlocos INT NOT NULL
		,Endereco VARCHAR(300) NULL
		,CEP VARCHAR(20) NULL
		,Bairro VARCHAR(100) NULL
		,CidadeID INT FOREIGN KEY (CidadeID) REFERENCES TB_CIDADE
		,Excluido BIT NOT NULL DEFAULT(0)
	)
END
GO

ALTER TABLE TB_CONDOMINIO
ADD DataFundacao DATE NULL