 IF NOT EXISTS(select * from sys.tables  where name = 'TB_ESTACIONAMENTO')
BEGIN
	CREATE TABLE TB_ESTACIONAMENTO
	(
		 EstacionamentoID INT PRIMARY KEY IDENTITY(1,1)
		,Nome VARCHAR(150) NOT NULL
		,QtdVagas INT NOT NULL
		,TipoEstacionamento CHAR(1)
		,CondominioID INT FOREIGN KEY (CondominioID) REFERENCES TB_CONDOMINIO
		,BlocoID INT FOREIGN KEY (BlocoID) REFERENCES TB_BLOCO NULL
	)
END
GO