IF NOT EXISTS(select * from sys.tables where name = 'TB_FUNCIONALIDADE_USUARIO')
BEGIN
	CREATE TABLE TB_FUNCIONALIDADE_USUARIO
	(
		 FuncionarioUser INT IDENTITY(1,1) PRIMARY KEY
		,FuncionalidadeID INT NOT NULL FOREIGN KEY(FuncionalidadeID) REFERENCES TB_FUNCIONALIDADE
		,UsuarioID INT NOT NULL FOREIGN KEY(UsuarioID) REFERENCES TB_USUARIO
		,Excluido BIT NOT  NULL DEFAULT(0)
	)
	END
GO

