IF NOT EXISTS(select * from sys.tables where name =  'TB_HORARIO')
BEGIN
	CREATE TABLE TB_HORARIO
	(
	 	 HorarioID INT PRIMARY KEY IDENTITY(1,1)
		,HoraInicio VARCHAR(50) NOT NULL
		,HoraFim VARCHAR(50) NULL
		,Excluido BIT NOT NULL DEFAULT(1)
	)
END
GO

ALTER TABLE TB_HORARIO
ADD AreaID INT NOT NULL FOREIGN KEY(AreaID) REFERENCES dbo.TB_AREA

ALTER TABLE TB_HORARIO
ADD Reservado BIT DEFAULT(0)



