IF NOT EXISTS(select * from sys.tables where name = 'TB_MORADOR')
BEGIN
	CREATE TABLE TB_MORADOR
	(
		 MoradorID INT PRIMARY KEY IDENTITY(1,1)
		,Nome VARCHAR(100) NOT NULL
		,RG VARCHAR(20) NULL
		,CPF VARCHAR(20) NULL
		,Email VARCHAR(20) NULL
		,CaminhoImagem VARCHAR(MAX) NULL
		,ApartamentoID INT FOREIGN KEY(ApartamentoID) REFERENCES TB_APARTAMENTO
	)
END
GO

ALTER TABLE TB_MORADOR
ADD UltimoNome VARCHAR(50) NOT NULL

ALTER TABLE TB_MORADOR
ADD DataNascimento DATE NOT NULL

ALTER TABLE TB_MORADOR
ADD VagaEstacionamentoID INT FOREIGN KEY (VagaEstacionamentoID) REFERENCES TB_VAGA_ESTACIONAMENTO

ALTER TABLE TB_MORADOR
ADD Excluido BIT NOT NULL DEFAULT(0)


