IF NOT EXISTS(select * from sys.tables where name = 'TB_TELEFONE_MORADOR')
BEGIN
	CREATE TABLE TB_TELEFONE_MORADOR
	(
		 TelefoneID INT FOREIGN KEY (TelefoneID) REFERENCES TB_TELEFONE
		,MoradorID INT FOREIGN KEY (MoradorID) REFERENCES TB_MORADOR
	)
END
GO