IF NOT EXISTS(select * from sys.tables where name = 'TB_USUARIO')
BEGIN
	CREATE TABLE TB_USUARIO
	(
		 UsuarioID INT PRIMARY KEY IDENTITY(1,1)
		,NomeUser VARCHAR(20) NOT NULL -- Nome de Usuário servira como login junto com a senha
		,Senha VARCHAR(20) NOT NULL		
		,CondominioID INT FOREIGN KEY(CondominioID) REFERENCES TB_CONDOMINIO

	)
	END
GO

ALTER TABLE TB_USUARIO
ADD TipoUsuario CHAR(1) NOT NULL
GO

ALTER TABLE TB_USUARIO
ADD BlocoID INT FOREIGN KEY(BlocoID) REFERENCES TB_BLOCO

ALTER TABLE TB_USUARIO 
ADD PredioID INT FOREIGN KEY(PredioID) REFERENCES TB_PREDIO

ALTER TABLE TB_USUARIO
ADD Excluido INT NOT NULL DEFAULT(0)

ALTER TABLE TB_USUARIO
ADD Email VARCHAR(200) NOT NULL
