IF NOT EXISTS(select * from sys.tables where name = 'TB_VAGA_ESTACIONAMENTO')
BEGIN
	CREATE TABLE TB_VAGA_ESTACIONAMENTO
	(
		 VagaEstacionamentoID INT PRIMARY KEY IDENTITY(1,1)
		,NumeroVaga VARCHAR(100) NOT NULL
		,TipoVaga BIT NOT NULL
		,ResevadaAluguel BIT NULL
		,EstacionamentoID INT FOREIGN KEY(EstacionamentoID) REFERENCES TB_ESTACIONAMENTO
	)
END
GO